new Schema("create_bic_bit:deep_frying")
	.simpleKey("results", "outputFluidOrItemArray")
	.simpleKey("ingredients", "inputFluidOrItemArray")
	.simpleKey("heatRequirement", "nonEmptyString", "superheated" || "heated" || "melt" || "frozen")
	.simpleKey("processingTime", "doubleNumber", 100)