new Schema("farmersdelight:cutting")
	.simpleKey("result", "outputItemArray")
	.simpleKey("ingredients", "inputItemArray")
	.dynamicKey((components, componentsBuilder) => components.get("inputItem")()
		.or(new componentsBuilder(2)
			.add(components.get("nonBlankString")().key("type"))
			.add(components.get("nonBlankString")().key("action"))
			.inputRole())
		.key("tool"))

new Schema("farmersdelight:cooking")
	.simpleKey("result", "outputItem")
	.simpleKey("ingredients", "inputItemArray")
	.simpleKey("container", "inputItem", null)
	.simpleKey("cookingtime", "intNumber", 200)
	.simpleKey("experience", "floatNumber", 1.0)
	.simpleKey("recipe_book_tab", "nonBlankString", null)