new Schema("stone_age:tree_stump")
	.simpleKey("result", "outputItem")
	.simpleKey("input", "inputItem")
	.simpleKey("tool", "inputItem")
	.simpleKey("chopTimes", "doubleNumber")

new Schema("stone_age:millstone")
	.simpleKey("result", "outputItem")
	.simpleKey("ingredient", "inputItem")
	.simpleKey("secondResult", "outputItem")
	.simpleKey("secondChance", "doubleNumber", 0.1)
	.simpleKey("activateCount", "doubleNumber", 1)

new Schema("stone_age:drying_rack")
	.simpleKey("result", "outputItem")
	.simpleKey("ingredient", "inputItem")
	.simpleKey("dryingTime", "doubleNumber", 100)