#KubeJS Client Properties
#Thu Mar 12 22:48:19 CST 2026
backgroundColor=2E3440
barBorderColor=ECEFF4
barColor=ECEFF4
blurScaledPackIcon=true
disableRecipeBook=false
exportAtlases=false
fmlLogColor=ECEFF4
fmlMemoryColor=ECEFF4
menuBackgroundBrightness=64
menuBackgroundScale=32.0
menuInnerBackgroundBrightness=32
overrideColors=false
showTagNames=true
title=The Winter Rescue [Dev] 0.7.0-20260312-build1 Minecraft 1.20.1*
