#KubeJS Client Properties
#Sat Aug 15 13:48:27 CST 2026
backgroundColor=2E3440
menuBackgroundBrightness=64
barBorderColor=ECEFF4
exportAtlases=false
disableRecipeBook=false
barColor=ECEFF4
title=The Winter Rescue [Experimental] 0.7.0-rc1-pre6 Minecraft 1.20.1*
overrideColors=false
fmlLogColor=ECEFF4
showTagNames=true
blurScaledPackIcon=true
fmlMemoryColor=ECEFF4
menuBackgroundScale=32.0
menuInnerBackgroundBrightness=32
