// you must also add in client_scripts/constants.js to disable them in JEI
const disabledItems = [
    // no tree punching
    'notreepunching:flint_axe',
    'notreepunching:flint_pickaxe',
    'notreepunching:flint_hoe',
    'notreepunching:flint_shovel',
    'notreepunching:macuahuitl',
    'notreepunching:gold_saw',
    'notreepunching:gold_knife',
    'notreepunching:gold_mattock',
    'notreepunching:andesite_cobblestone', 'notreepunching:diorite_cobblestone', 'notreepunching:granite_cobblestone', 'notreepunching:andesite_loose_rock', 'notreepunching:diorite_loose_rock', 'notreepunching:granite_loose_rock', 'notreepunching:andesite_cobblestone_stairs', 'notreepunching:diorite_cobblestone_stairs', 'notreepunching:granite_cobblestone_stairs',
    'notreepunching:andesite_cobblestone_slab', 'notreepunching:diorite_cobblestone_slab', 'notreepunching:granite_cobblestone_slab', 'notreepunching:andesite_cobblestone_wall', 'notreepunching:diorite_cobblestone_wall', 'notreepunching:granite_cobblestone_wall', 'notreepunching:stone_loose_rock', 'notreepunching:sandstone_loose_rock', 'notreepunching:red_sandstone_loose_rock',
    'notreepunching:plant_string',
    'notreepunching:plant_fiber',
    'notreepunching:clay_brick',
    'notreepunching:ceramic_small_vessel',
    'notreepunching:ceramic_large_vessel',
    'notreepunching:flint_shard',

    // stone age
    'stone_age:copper_hammer',
    'stone_age:bronze_hammer',
    'stone_age:stone_hammer',

    // ie
    'immersiveengineering:toolbox',
    'immersiveengineering:sorter',
    'immersiveengineering:fluid_sorter',

    // rankine items
    'rankine:element_transmuter',
    'rankine:up_transmuter',
    'rankine:down_transmuter',
    'rankine:left_transmuter',
    'rankine:right_transmuter',
    'rankine:totem_of_cobbling',
    'rankine:thermometer',
    'rankine:alloy_plate',
    'rankine:alloy_ingot',
    'rankine:alloy_gear',
    'rankine:totem_of_cobbling',
    'rankine:element_indexer',
    // 'rankine:power_cell',
    // 'rankine:power_cell_2',
    // 'rankine:power_cell_3',
    // 'rankine:power_cell_4',
    // 'rankine:power_cell_5',
    // 'rankine:power_cell_6',
    'rankine:steel_gold_pan',


    // rankine machines
    'rankine:alloy_furnace',
    'rankine:induction_furnace',
    'rankine:piston_crusher',
    'rankine:gyratory_crusher',
    'rankine:template_table',
    'rankine:alloy_template',
    'rankine:crucible',
    'rankine:laser_pylon_base',
    'rankine:laser_pylon_top',
    'rankine:laser_quarry',
    'rankine:botanist_station',
    'rankine:diamond_anvil_cell',
    'rankine:rankine_box',
    'rankine:sediment_fan',
    'rankine:rare_earth_electromagnet',
    'rankine:alnico_electromagnet',
    'rankine:charcoal_pit',

    // create
    'create:water_wheel',
    // 'create:cogwheel',
    // 'create:large_cogwheel',
    'create:wand_of_symmetry',
    'create:mechanical_piston',
    'create:sticky_mechanical_piston',
    'create:piston_extension_pole',
    'create:gantry_carriage',
    'create:gantry_shaft',
    'create:windmill_bearing',
    'create:mechanical_bearing',
    'create:clockwork_bearing',
    'create:rope_pulley',
    'create:cart_assembly',
    'create:sticker',
    'create:mechanical_drill',
    'create:flywheel',
    'create:furnace_engine',
    'create:schematicannon',
    'create:mechanical_plough'
]