[Miscellaneous]
	#BlackListed mods to kick player
	"Mod Blacklist" = []

[AutoUpdate]
	#Enable update reminder if later snapshot was found, DONT TOUCH UNLESS INSTRUCTED BY DEV TEAM.
	enableUpdateReminder = true

