Ponder.registry((event) => {
    event.create(["charcoal_pit:clay_pot", "charcoal_pit:straw"])
        .tag("charcoal_pit:ponder")
        .scene("basic_usage", "", "kubejs:pottery_kiln", (scene) => {
            scene.showBasePlate()
            scene.idle(20)

            scene.addKeyframe()
            scene.showControls(20, [2, 1.5, 2], "right")
                .withItem("minecraft:cobblestone")
                .rightClick()
                .whileSneaking()
            scene.idle(20)
            scene.world.showSection([2, 1, 2], Direction.DOWN)
            scene.idle(20)

            scene.addKeyframe()
            scene.showControls(20, [2, 1.5, 2], "right")
                .withItem("charcoal_pit:straw")
                .rightClick()
            scene.idle(20)
            let move1 = scene.world.showIndependentSectionImmediately([2, 3, 2])
            scene.world.moveSection(move1, [0, -2, 0], 0)
            scene.idle(20)

            scene.addKeyframe()
            scene.showControls(20, [2, 1.5, 2], "right")
                .withItem("minecraft:oak_log")
                .rightClick()
            scene.idle(20)

            let move2 = scene.world.showIndependentSectionImmediately([2, 5, 2])
            scene.world.moveSection(move2, [0, -4, 0], 0)
            scene.idle(20)

            scene.addKeyframe()
            scene.world.showSection([2, 1, 1], Direction.DOWN)
            scene.world.showSection([1, 1, 2], Direction.DOWN)
            scene.world.showSection([2, 1, 3], Direction.DOWN)
            scene.world.showSection([3, 1, 2], Direction.DOWN)
            scene.idle(20)
            scene.text(40, "Put solid blocks all around, not necessarily limited to dirt")
            scene.overlay.showOutline("blue", {}, [2, 1, 1], 40)
            scene.overlay.showOutline("blue", {}, [1, 1, 2], 40)
            scene.overlay.showOutline("blue", {}, [2, 1, 3], 40)
            scene.overlay.showOutline("blue", {}, [3, 1, 2], 40)
            scene.idle(40)

            scene.addKeyframe()
            scene.showControls(20, [2, 2.5, 2], "right")
                .withItem("charcoal_pit:fire_starter")
                .rightClick()
            let move3 = scene.world.showIndependentSectionImmediately([2, 7, 2])
            scene.world.moveSection(move3, [0, -5, 0], 0)

            scene.world.modifyBlocks([2, 1, 2], (state) => state.with("kiln_type", "active"))
            scene.idle(20)
        })
})