Ponder.registry((event) => {
    event.create(["frostedheart:house", "frostedheart:warehouse"])
        .tag("frostedheart:town_ponder")
        .scene("building_general", "Town Building General", "kubejs:town_building", (scene, util) => {
            //整个结构为10 * 10 * 10
            scene.showBasePlate()
            scene.idle(20)

            scene.text(50, "尽管城镇建筑的要求各不相同，但它们通常有一些共性").attachKeyFrame()
            scene.idle(50)
            scene.text(60, "例如，一个简单的房屋结构可以这样搭建：")
            //显示结构
            for (let i = 1; i < 10; i++) {
                scene.world.showSection([0, i, 0, 9, i, 9], Direction.DOWN)
                scene.idle(15)
            }
            scene.idle(30)

            scene.text(30, "城镇建筑通常需要一扇门", [1, 2, 3.5]).attachKeyFrame()
            scene.idle(40)
            scene.text(40, "并将主方块放在门旁边", [1, 2.5, 4.5])
            scene.idle(50)

            scene.text(70, "建筑的墙壁可以替换为任意具有完整碰撞箱的固体方块").attachKeyFrame()
            scene.idle(30)
            scene.world.replaceBlocks([2, 1, 1, 9, 4, 9], "minecraft:bricks", true)
            scene.world.replaceBlocks([1, 1, 1, 1, 4, 2], "minecraft:bricks", true)
            scene.world.replaceBlocks([1, 1, 5, 1, 4, 9], "minecraft:bricks", true)
            scene.world.replaceBlocks([1, 3, 3, 1, 4, 4], "minecraft:bricks", true)
            scene.world.replaceBlocks([1, 4, 1], "minecraft:bricks", true)
            scene.idle(40)

            scene.text(120, "也可以替换成玻璃板、墙、栅栏、门、栅栏门").attachKeyFrame()
            scene.idle(20)
            scene.world.replaceBlocks([3, 2, 1, 6, 3, 1], "minecraft:stone_brick_wall", true)
            scene.world.modifyBlock([3, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([4, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([5, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([6, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([3, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([4, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([5, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([6, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.idle(30)
            scene.world.replaceBlocks([3, 2, 1, 6, 3, 1], "minecraft:oak_fence", true)
            scene.world.modifyBlock([3, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([4, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([5, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([6, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([3, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([4, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([5, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([6, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.idle(30)
            scene.world.replaceBlocks([3, 2, 1, 6, 3, 1], "minecraft:oak_fence_gate", true)
            scene.world.modifyBlock([3, 2, 1], (state) => state.with("facing", "south"), true)
            scene.world.modifyBlock([4, 2, 1], (state) => state.with("facing", "south"), true)
            scene.world.modifyBlock([5, 2, 1], (state) => state.with("facing", "south"), true)
            scene.world.modifyBlock([6, 2, 1], (state) => state.with("facing", "south"), true)
            scene.world.modifyBlock([3, 3, 1], (state) => state.with("facing", "south"), true)
            scene.world.modifyBlock([4, 3, 1], (state) => state.with("facing", "south"), true)
            scene.world.modifyBlock([5, 3, 1], (state) => state.with("facing", "south"), true)
            scene.world.modifyBlock([6, 3, 1], (state) => state.with("facing", "south"), true)
            scene.idle(30)
            scene.world.replaceBlocks([3, 2, 1, 6, 3, 1], "minecraft:glass_pane", true)
            scene.world.modifyBlock([3, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([4, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([5, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([6, 2, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([3, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([4, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([5, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.world.modifyBlock([6, 3, 1], (state) => state.with("west", "true").with("east", "true"), true)
            scene.idle(40)

            scene.text(100, "类似的，房屋的屋顶和地板也可以替换成任意具有完整碰撞箱的固体方块").attachKeyFrame()
            scene.idle(20)
            scene.world.hideSection([0, 0, 0, 1, 9, 9], Direction.WEST)
            scene.world.hideSection([0, 0, 0, 9, 9, 1], Direction.NORTH)

            scene.idle(40)
            scene.world.replaceBlocks([2, 0, 2, 8, 0, 8], "minecraft:deepslate_tiles", true)
            scene.world.replaceBlocks([2, 5, 2, 8, 5, 8], "minecraft:deepslate_tiles", true)
            scene.idle(40)

            scene.text(130, "也可以替换成任意台阶和半砖").attachKeyFrame()
            scene.idle(30)
            scene.world.replaceBlocks([2, 0, 2, 8, 0, 8], "minecraft:oxidized_cut_copper_stairs", true)
            scene.world.replaceBlocks([2, 5, 2, 8, 5, 8], "minecraft:oxidized_cut_copper_stairs", true)
            scene.idle(30)
            scene.world.replaceBlocks([2, 0, 2, 8, 0, 8], "minecraft:smooth_stone_slab", true)
            scene.world.replaceBlocks([2, 5, 2, 8, 5, 8], "minecraft:smooth_stone_slab", true)
            scene.idle(30)
            scene.world.replaceBlocks([2, 0, 2, 8, 0, 8], "minecraft:stone_bricks", true)
            scene.world.replaceBlocks([2, 5, 2, 8, 5, 8], "minecraft:stone_bricks", true)
            scene.idle(40)
            scene.text(100, "城镇的结构通常可以任意的改变形状和大小").attachKeyFrame()
            scene.world.showSection([0, 0, 0, 9, 9, 9], Direction.UP)
            scene.world.replaceBlocks([0, 0, 0, 9, 0, 9], "supplementaries:checker_block", false)
            //演示改变大小和形状
            scene.idle(30)
            scene.world.setBlocks([6, 1, 1, 8, 4, 8], "minecraft:air", true)
            scene.world.setBlocks([5, 5, 1, 8, 5, 8], "minecraft:air", true)
            scene.world.setBlocks([5, 1, 1, 5, 4, 8], "minecraft:bricks", true)
            scene.idle(60)
            scene.addKeyframe()
            scene.idle(40)
            //移除3*3的天花板
            scene.world.setBlocks([2, 5, 2, 4, 5, 4], "minecraft:air", true)
            scene.world.setBlocks([1, 5, 1, 5, 7, 5], "minecraft:bricks", true)
            scene.world.setBlocks([2, 5, 2, 4, 6, 4], "minecraft:air", true)
            scene.world.replaceBlocks([2, 2, 1, 4, 6, 1], "minecraft:glass_pane", false)
            for (let i = 2; i <= 6; i++) {
                for (let j = 2; j <= 4; j++) {
                    scene.world.modifyBlock([j, i, 1], (state) => state.with("west", "true").with("east", "true"), true)
                }
            }
            scene.idle(60)
            scene.text(100, "但多个建筑的在xz面上的投影不可重叠，也就是不允许多个建筑共用一片区域，也不可在竖直方向上堆叠。").colored(PonderPalette.RED).attachKeyFrame()
            scene.idle(20)
            scene.world.replaceBlocks([1, 2, 2], "frostedheart:house", true)
            scene.idle(10)
            scene.overlay.showOutline("red", {}, [1, 0, 1, 5, 7, 8], 30)
            scene.overlay.showOutline("red", {}, [1, 2, 2], 30)
            scene.overlay.showOutline("red", {}, [1, 2, 4], 30)
            scene.idle(50)
            scene.world.replaceBlocks([1, 2, 2], "minecraft:bricks", true)
            scene.idle(20)
            scene.overlay.showOutline("green", {}, [1, 0, 1, 5, 7, 8], 30)
            scene.idle(60)

        })

    //house特有
    event.create(["frostedheart:house"])
        .tag("frostedheart:town_ponder")
        .scene("house_structure", "Building a House", "kubejs:town_building", (scene, util) => {
            scene.showBasePlate()
            scene.idle(20)

            scene.text(90, "一个合格的城镇房屋需要有一个完全封闭空间").attachKeyFrame().colored(PonderPalette.RED).attachKeyFrame()
            //显示结构
            for (let i = 1; i < 6; i++) {
                scene.world.showSection([0, i, 0, 9, i, 9], Direction.DOWN)
                scene.idle(20)
            }
            scene.text(100, "任何墙壁或天花板的破损都会导致结构判定失败").attachKeyFrame()
            scene.world.setBlocks([1, 3, 2], "minecraft:air", true)
            scene.idle(5)
            scene.world.setBlocks([6, 2, 1], "minecraft:air", true)
            scene.idle(5)
            scene.world.setBlocks([3, 5, 4], "minecraft:air", true)
            scene.idle(10)
            scene.overlay.showOutline("red", {}, [1, 3, 2], 30)
            scene.overlay.showOutline("red", {}, [6, 2, 1], 30)
            scene.overlay.showOutline("red", {}, [3, 5, 4], 30)
            scene.overlay.showOutline("red", {}, [1, 0, 1, 8, 5, 8], 30)
            scene.idle(50)

            scene.world.setBlocks([1, 3, 2], "minecraft:stone_bricks", true)
            scene.world.setBlocks([6, 2, 1], "minecraft:stone_bricks", true)
            scene.world.setBlocks([3, 5, 4], "minecraft:stone_bricks", true)
            scene.idle(10)
            scene.overlay.showOutline("green", {}, [1, 0, 1, 8, 5, 8], 30)
            scene.idle(50)

            scene.world.replaceBlocks([2, 1, 1, 9, 4, 1], "minecraft:glass", false)
            scene.world.replaceBlocks([1, 1, 1, 1, 4, 2], "minecraft:glass", false)
            scene.world.replaceBlocks([1, 1, 5, 1, 4, 9], "minecraft:glass", false)
            scene.world.replaceBlocks([1, 3, 3, 1, 4, 4], "minecraft:glass", false)
            scene.world.replaceBlocks([1, 4, 1], "minecraft:glass", false)
            scene.idle(60)
            scene.text(75, "与房屋方块旁的门连接的所有有效地板的数量会被判定为有效面积").attachKeyFrame()
            scene.idle(20)
            scene.overlay.showOutline("white", {}, [2, 0, 2, 7, 0, 7], 30)
            scene.idle(60)
            scene.text(80, "封闭房屋内的所有空间会被判定为有效体积").attachKeyFrame()
            scene.idle(20)
            scene.overlay.showOutline("white", {}, [2, 1, 2, 7, 4, 7], 30)
            scene.idle(60)
        })

    event.create(["frostedheart:warehouse"])
        .tag("frostedheart:town_ponder")
        .scene("warehouse_structure", "Building a Warehouse", "kubejs:town_warehouse", (scene, util) => { 
            scene.showBasePlate()
            scene.idle(20)

            scene.text(90, "一个合格的城镇仓库不需要完全封闭的空间，但需要封闭的围墙以及完整的天花板").attachKeyFrame().colored(PonderPalette.RED).attachKeyFrame()
            //显示结构
            for (let i = 1; i < 6; i++) {
                scene.world.showSection([0, i, 0, 7, i, 7], Direction.DOWN)
                scene.idle(20)
            }
            scene.text(60, "结构内的任何有效地板上方不存在天花板时，结构会判定失败").attachKeyFrame()
            scene.idle(10)
            scene.world.setBlocks([3,4,3], "minecraft:air", true)
            scene.idle(20)
            scene.overlay.showOutline("red", {}, [3,4,3], 30)
            scene.overlay.showOutline("red", {}, [1,0,1,6,4,6], 30)
            scene.idle(30)
            scene.world.setBlocks([3,4,3], "minecraft:stone_bricks", true)
            scene.idle(20)
            scene.text(60, "结构的墙壁上若有足够一人通过的缺口，结构会判定失败").attachKeyFrame()
            scene.idle(10)
            scene.world.setBlocks([1, 2, 2], "minecraft:air", true)
            scene.idle(5)
            scene.world.setBlocks([4, 1, 1, 4, 2, 1], "minecraft:air", true)
            scene.idle(20)
            scene.overlay.showOutline("red", {}, [1,2,2,1,3,2], 30)
            scene.overlay.showOutline("red", {}, [4,1,1,4,2,1], 30)
            scene.idle(5)
            scene.overlay.showOutline("red", {}, [1,0,1,6,4,6], 30)
            scene.idle(60)
            scene.world.setBlocks([1, 2, 2], "minecraft:stone_bricks", true)
            scene.idle(5)
            scene.world.setBlocks([4, 1, 1, 4, 2, 1], "minecraft:stone_bricks", true)
            scene.text(70, "墙壁上的缺口不足一人通过时，不影响结构判定").attachKeyFrame()
            scene.idle(20)
            scene.world.setBlocks([3,1,1], "minecraft:air", true)
            scene.idle(10)
            scene.world.setBlocks([5,2,1], "minecraft:air", true)
            scene.world.setBlocks([5,3,1], "minecraft:stone_bricks", true)
            scene.idle(20)
            scene.overlay.showOutline("green", {}, [3,1,1], 30)
            scene.overlay.showOutline("green", {}, [5,2,1], 30)
            scene.idle(10)
            scene.overlay.showOutline("green", {}, [1,0,1,6,4,6], 30)
            scene.idle(60)

            scene.addKeyframe()
            scene.world.setBlocks([3,1,1], "minecraft:stone_bricks", false)
            scene.world.setBlocks([5,2,1], "minecraft:stone_bricks", false)
            scene.world.setBlocks([5,3,1], "minecraft:air", false)
            
            scene.world.replaceBlocks([1,1,1, 5,2,1], "minecraft:glass", false)
            scene.world.replaceBlocks([1,1,2, 1,2,2], "minecraft:glass", false)
            scene.world.replaceBlocks([1,1,4], "minecraft:glass", false)
            scene.world.replaceBlocks([1,1,5, 1,2,5], "minecraft:glass", false)
            scene.world.replaceBlocks([2,4,2,5,4,5], "minecraft:glass", false)
            scene.idle(20)
            scene.text(60, "与房屋方块旁的门连接的所有有效地板的数量会被判定为有效面积")
            scene.overlay.showOutline("white", {}, [2, 0, 2, 5, 0, 5], 30)
            scene.idle(70)
            scene.text(60, "所有有效地板到有效天花板之间的空间会被判定为有效体积")
            scene.overlay.showOutline("white", {}, [2, 1, 2, 5, 3, 5], 30)
            scene.idle(60)
        })
        
        //MineBase
        event.create(["frostedheart:mine_base"])
        .tag("frostedheart:town_ponder")
        .scene("mine_base_structure", "Building a Mine Base", "kubejs:town_warehouse", (scene, util) => { 
            scene.showBasePlate()
            scene.idle(20)

            scene.text(90, "一个合格的矿场基地不需要完全封闭的空间，但需要封闭的围墙以及完整的天花板").attachKeyFrame().colored(PonderPalette.RED).attachKeyFrame()
            //显示结构
            for (let i = 1; i < 6; i++) {
                scene.world.showSection([0, i, 0, 7, i, 7], Direction.DOWN)
                if(i == 2){
                    scene.world.replaceBlocks([1,2,4], "frostedheart:mine_base", false)
                }
                scene.idle(20)
            }
            scene.text(60, "结构内的任何有效地板上方不存在天花板时，结构会判定失败").attachKeyFrame()
            scene.idle(10)
            scene.world.setBlocks([3,4,3], "minecraft:air", true)
            scene.idle(20)
            scene.overlay.showOutline("red", {}, [3,4,3], 30)
            scene.overlay.showOutline("red", {}, [1,0,1,6,4,6], 30)
            scene.idle(30)
            scene.world.setBlocks([3,4,3], "minecraft:stone_bricks", true)
            scene.idle(20)
            scene.text(60, "结构的墙壁上若有足够一人通过的缺口，结构会判定失败").attachKeyFrame()
            scene.idle(10)
            scene.world.setBlocks([1, 2, 2], "minecraft:air", true)
            scene.idle(5)
            scene.world.setBlocks([4, 1, 1, 4, 2, 1], "minecraft:air", true)
            scene.idle(20)
            scene.overlay.showOutline("red", {}, [1,2,2,1,3,2], 30)
            scene.overlay.showOutline("red", {}, [4,1,1,4,2,1], 30)
            scene.idle(5)
            scene.overlay.showOutline("red", {}, [1,0,1,6,4,6], 30)
            scene.idle(60)
            scene.world.setBlocks([1, 2, 2], "minecraft:stone_bricks", true)
            scene.idle(5)
            scene.world.setBlocks([4, 1, 1, 4, 2, 1], "minecraft:stone_bricks", true)
            scene.text(70, "墙壁上的缺口不足一人通过时，不影响结构判定").attachKeyFrame()
            scene.idle(20)
            scene.world.setBlocks([3,1,1], "minecraft:air", true)
            scene.idle(10)
            scene.world.setBlocks([5,2,1], "minecraft:air", true)
            scene.world.setBlocks([5,3,1], "minecraft:stone_bricks", true)
            scene.idle(20)
            scene.overlay.showOutline("green", {}, [3,1,1], 30)
            scene.overlay.showOutline("green", {}, [5,2,1], 30)
            scene.idle(10)
            scene.overlay.showOutline("green", {}, [1,0,1,6,4,6], 30)
            scene.idle(60)

            scene.addKeyframe()
            scene.world.setBlocks([3,1,1], "minecraft:stone_bricks", false)
            scene.world.setBlocks([5,2,1], "minecraft:stone_bricks", false)
            scene.world.setBlocks([5,3,1], "minecraft:air", false)
            
            scene.world.replaceBlocks([1,1,1, 5,2,1], "minecraft:glass", false)
            scene.world.replaceBlocks([1,1,2, 1,2,2], "minecraft:glass", false)
            scene.world.replaceBlocks([1,1,4], "minecraft:glass", false)
            scene.world.replaceBlocks([1,1,5, 1,2,5], "minecraft:glass", false)
            scene.world.replaceBlocks([2,4,2,5,4,5], "minecraft:glass", false)
            scene.idle(20)
            scene.text(60, "与房屋方块旁的门连接的所有有效地板的数量会被判定为有效面积")
            scene.overlay.showOutline("white", {}, [2, 0, 2, 5, 0, 5], 30)
            scene.idle(70)
            scene.text(60, "所有有效地板到有效天花板之间的空间会被判定为有效体积")
            scene.overlay.showOutline("white", {}, [2, 1, 2, 5, 3, 5], 30)
            scene.idle(60)
        })

    //多层建筑
    event.create(["frostedheart:house", "frostedheart:warehouse"])
        .tag("frostedheart:town_ponder")
        .scene("2_story_building", "Multi story building", "kubejs:town_2_story_house", (scene, util) => {
            scene.showBasePlate()
            scene.idle(20)

            scene.text(60, "你可以建造具有多层结构的建筑，以扩大有效面积，以城镇房屋为例").attachKeyFrame()
            //显示结构
            for (let i = 1; i < 11; i++) {
                scene.world.showSection([0, i, 0, 9, i, 9], Direction.DOWN)
                scene.idle(5)
            }
            scene.idle(40)
            scene.text(60, "你可以用方块搭建楼梯来连接到其它楼层").attachKeyFrame()
            for (let i = 0; i < 3; i++) {
                scene.world.setBlocks([5, 1 + i, 3 + i], "minecraft:oak_planks", false)
                scene.idle(10)
            }
            scene.idle(20)
            scene.overlay.showOutline("white", {}, [2, 3, 2, 4, 3, 5], 30)
            scene.idle(50)

            scene.text(60, "你也可以使用梯子连接楼层").attachKeyFrame()
            for (let i = 0; i < 3; i++) {
                scene.world.setBlocks([5, 1 + i, 3 + i], "minecraft:air", false)
                scene.idle(5)
            }
            scene.world.setBlocks([5, 1, 2, 5, 3, 2], "minecraft:ladder", true)
            for (let i = 0; i < 3; i++) {
                scene.world.modifyBlock([5, 1 + i, 2], (state) => state.with("facing", "west"), false)
            }
            scene.idle(40)
            scene.overlay.showOutline("white", {}, [2, 3, 2, 4, 3, 5], 30)
            scene.idle(60)
        })
})