ServerEvents.tags("fluid", (event) => {
    event.add("forge:steam", "steampowered:steam")
    event.add("frostedheart:hot_drink", "steampowered:steam")
    event.add("frostedheart:drink", "steampowered:steam")
    event.add("frostedheart:drink", "minecraft:milk")
    event.add("the_winter_rescue:fluidsulfuricacid", "frostedheart:sulfuric_acid")
    event.add("the_winter_rescue:cryolite", "frostedheart:cryolite")
    event.add("the_winter_rescue:magnesium_chloride", "frostedheart:magnesium_chloride")
    event.add("the_winter_rescue:ferric_chloride", "frostedheart:ferric_chloride")
    event.add("the_winter_rescue:copper_chloride", "frostedheart:copper_chloride")
    event.add("forge:gas/fluorine", "frostedheart:fluorine")
    event.add("forge:gas/chlorine", "frostedheart:chlorine")
    event.add("forge:acid/hydrochloric", "frostedheart:hydrochloric_acid")
    event.add("the_winter_rescue:ferrous_chloride", "frostedheart:ferrous_chloride")
    event.add("the_winter_rescue:zinc_sulfate", "frostedheart:zinc_sulfate")
    event.add("caupona:stews", "minecraft:water")
})