Ponder.registry((event) => {
    event.create(["immersiveindustry:crucible", "immersiveindustry:burning_chamber", "frostedheart:high_refractory_bricks", "immersiveengineering:blastfurnace_preheater"])
        .tag("immersiveindustry:ponder")
        // Build
        .scene("assembly", "", "kubejs:steel_mill_crucible", (scene) => {
            scene.showBasePlate()
            scene.idle(20)

            // Generic build
            scene.world.showSection([4, 1, 0, 0, 1, 4], Direction.DOWN)
            scene.addKeyframe()
            scene.idle(40)
            scene.world.showSection([4, 2, 0, 0, 2, 4], Direction.DOWN)
            scene.addKeyframe()
            scene.idle(40)
            scene.world.showSection([4, 3, 0, 0, 3, 4], Direction.DOWN)
            scene.addKeyframe()
            scene.idle(40)
            scene.world.showSection([4, 4, 0, 0, 4, 4], Direction.DOWN)
            scene.addKeyframe()
            scene.idle(40)

            // text
            scene.addKeyframe()
            scene.overlay.showOutline("blue", {}, [2.5, 2.5, 1], 40)
            scene.overlay.showText(40)
                .text("R-Click to assemble")
                .pointAt([2.5, 2.5, 1])
            scene.idle(40)
            scene.showControls(40, [2, 2, 1], "right")
                .withItem("immersiveengineering:hammer")
            scene.world.moveSection(scene.world.showIndependentSectionImmediately([1, 6, 1, 3, 10, 3]), [0, -5, 0], 0)
            scene.world.replaceBlocks([1, 1, 1, 3, 4, 3], "minecraft:air", true)
            scene.idle(40)
            scene.addKeyframe()

            scene.rotateCameraY(180)
            scene.idle(20)
            scene.overlay.showText(40)
                .text("Install Preheater here")
                .pointAt([2.5, 1.5, 4.5])
            scene.idle(20)
            scene.world.moveSection(scene.world.showIndependentSection([0, 6, 4, 4, 10, 4], Direction.NORTH), [0, -5, 0], 0)
            scene.idle(60)
        })

        // Usage
        .scene("basic_usage", "", "kubejs:steel_mill_crucible_usage", (scene) => {
            scene.showBasePlate()
            scene.idle(20)

            scene.world.showSection([5, 1, 0], Direction.DOWN)
            scene.world.showSection([1, 1, 2, 3, 4, 4], Direction.DOWN)
            scene.idle(20)
            // text
            scene.overlay.showText(40)
                .text("Install Preheater here")
                .pointAt([2.5, 1, 1.5])
            scene.idle(20)
            scene.world.showSection([2, 1, 1, 2, 4, 1], Direction.SOUTH)
            scene.idle(20)
            scene.overlay.showText(40)
                .text("Power must be provided here")
                .pointAt([2.5, 4.5, 1.5])
            scene.idle(40)
            scene.addKeyframe()
            scene.overlay.showText(20)
                .text("You can either use GUI or automation input")
                .pointAt([1, 1, 2])
            scene.idle(40)

            // scene.addKeyframe()
            // scene.overlay.showText(20)
            //     .text("Ingredients can be throw into crucible")
            //     .pointAt([2, 5, 3])
            // scene.idle(20)
            // scene.showControls(10, [2, 5, 3], "up")
            //     .withItem("frostedheart:flux")
            // scene.idle(12)
            // scene.world.createItemEntity([2.5, 5, 3.5], Direction.DOWN, "frostedheart:flux")
            // scene.idle(20)
            // scene.showControls(10, [2, 5, 3], "up")
            //     .withItem("minecraft:iron_ingot")
            // scene.idle(12)
            // scene.world.createItemEntity([2.5, 5, 3.5], Direction.DOWN, "minecraft:iron_ingot")
            // scene.idle(40)

            scene.addKeyframe()
            scene.overlay.showText(40)
                .text("Ingredients can also insert into crucible on the top")
                .pointAt([2.5, 5.5, 2.5])
            scene.world.showSection([2, 5, 2], Direction.DOWN)
            scene.idle(40)
            scene.addKeyframe()
            scene.rotateCameraY(90)
            scene.idle(20)
            scene.world.showSection([4, 1, 0, 5, 2, 5], Direction.WEST)
            scene.overlay.showText(40)
                .text("Coke coal can insert to the burners")
                .pointAt([4.5, 1.5, 3.5])
            let coalCokeItem = scene.world.createItemEntity([4.5, 3, 3.5], Direction.DOWN, "immersiveengineering:coal_coke")
            scene.idle(9)
            scene.world.removeEntity(coalCokeItem)
            scene.idle(40)
            scene.addKeyframe()
            scene.world.showSection([5, 3, 4, 4, 4, 3], Direction.WEST)
            scene.overlay.showText(40)
                .text("Products can be extracted from sides of the crucible part")
                .pointAt([4.5, 4.5, 3.5])
            scene.idle(20)
            scene.world.createItemOnBelt([4, 3, 3], Direction.UP, "frostedheart:steel_ingot");
            scene.idle(40)
        })
})