LootJS.modifiers((event) => {
    // vines and sticks
    event.addBlockLootModifier("#minecraft:leaves")
        .matchMainHand("#minecraft:swords")
        .randomChance(0.75)
        .addLoot("minecraft:vine")
        .randomChance(0.75)
        .addLoot("minecraft:stick")
        .randomChance(0.03)
        .addLoot("frostedheart:frozen_seeds")
    // ice chips
    event.addBlockLootModifier("frostedheart:thin_ice")
        .removeLoot("frostedheart:ice_chip")
        .randomChance(1.0)
        .addLoot("frostedheart:ice_chip x1")
        .randomChance(0.3)
        .addLoot("frostedheart:ice_chip x2")
    event.addBlockLootModifier("minecraft:ice")
        .randomChance(1.0)
        .addLoot("frostedheart:ice_chip x1")
        .randomChance(0.5)
        .addLoot("frostedheart:ice_chip x2")
    event.addBlockLootModifier("minecraft:packed_ice")
        .randomChance(1.0)
        .addLoot("frostedheart:ice_chip x1")
        .randomChance(0.7)
        .addLoot("frostedheart:ice_chip x2")
    event.addBlockLootModifier("minecraft:blue_ice")
        .randomChance(1.0)
        .addLoot("frostedheart:ice_chip x2")
        .randomChance(0.9)
        .addLoot("frostedheart:ice_chip x2")

    event.addBlockLootModifier("frostedheart:besnowed_debris")
        .randomChance(0.7)
        .addLoot("minecraft:flint")
        .randomChance(0.3)
        .addLoot("minecraft:flint")
        .randomChance(0.03)
        .addLoot("frostedheart:frozen_seeds")
        .randomChance(0.2)
        .addLoot("frostedheart:iron_fence_remains")
        .randomChance(0.01)
        .addLoot('frostedheart:ferrocerium_fire_starter')
        .randomChance(0.2)
        .addLoot('frostedheart:iron_parts')
        .randomChance(0.2)
        .addLoot('frostedheart:iron_truss_remains')
        .randomChance(0.2)
        .addLoot('frostedheart:insulator')

    event.addBlockLootModifier("frostedheart:besnowed_twigs")
        .randomChance(1.0)
        .addLoot("minecraft:stick")
        .randomChance(0.5)
        .addLoot("minecraft:vine")
        .randomChance(0.03)
        .addLoot("frostedheart:frozen_seeds")
        .randomChance(0.01)
        .addLoot("frostedheart:iron_fence_remains")
        .randomChance(0.01)
        .addLoot('frostedheart:ferrocerium_fire_starter')
        .randomChance(0.01)
        .addLoot('frostedheart:iron_parts')
        .randomChance(0.01)
        .addLoot('frostedheart:iron_truss_remains')
        .randomChance(0.01)
        .addLoot('frostedheart:insulator')

    event.addBlockLootModifier("frostedheart:small_garage")
        .randomChance(1.0)
        .addLoot("frostedheart:frozen_seeds")
        .randomChance(0.05)
        .addLoot("frostedheart:dried_wolfberries")
        .randomChance(0.5)
        .addLoot("frostedheart:rye")
        .randomChance(0.5)
        .addLoot("frostedheart:rye_flour")
        .randomChance(0.5)
        .addLoot("frostedheart:raw_rye_bread")
        .randomChance(0.5)
        .addLoot("frostedheart:random_seeds")
        .randomChance(0.5)
        .addLoot("frostedheart:rye_bread")
        .randomChance(0.5)
        .addLoot("frostedheart:black_bread")
        .randomChance(0.5)
        .addLoot("frostedheart:vegetable_sawdust_soup")
        .randomChance(0.5)
        .addLoot("frostedheart:rye_sawdust_soup")
        .randomChance(0.5)
        .addLoot("frostedheart:rye_porridge")
        .randomChance(0.5)
        .addLoot("frostedheart:vegetable_soup")
        .randomChance(0.5)
        .addLoot("frostedheart:military_rations")
        .randomChance(0.5)
        .addLoot("frostedheart:compressed_biscuit_pack")
        .randomChance(0.5)
        .addLoot("frostedheart:compressed_biscuits")
        .randomChance(0.5)
        .addLoot("frostedheart:packed_nuts")
        .randomChance(0.5)
        .addLoot("frostedheart:dried_vegetables")
        .randomChance(0.5)
        .addLoot("frostedheart:chocolate")

    event.addBlockLootModifier("frostedheart:package_block")
        .addLoot("frostedheart:iron_fence_remains")
        .randomChance(0.5)
        .addLoot('frostedheart:ferrocerium_fire_starter')
        .randomChance(0.5)
        .addLoot('frostedheart:iron_parts')
        .randomChance(0.5)
        .addLoot('frostedheart:iron_truss_remains')
        .randomChance(0.5)
        .addLoot('frostedheart:insulator')

    event.addBlockLootModifier("frostedheart:wooden_box")
        .addLoot("frostedheart:iron_fence_remains")
        .randomChance(0.5)
        .addLoot('frostedheart:ferrocerium_fire_starter')
        .randomChance(0.5)
        .addLoot('frostedheart:iron_parts')
        .randomChance(0.5)
        .addLoot('frostedheart:iron_truss_remains')
        .randomChance(0.5)
        .addLoot('frostedheart:insulator')

    // Change IE ore drops: They do appear sometimes...just to avoid issues
    event.addBlockLootModifier('immersiveengineering:ore_aluminum')
        .replaceLoot('immersiveengineering:raw_aluminum', 'frostedheart:bauxite')

    event.addBlockLootModifier('immersiveengineering:deepslate_ore_aluminum')
        .replaceLoot('immersiveengineering:raw_aluminum', 'frostedheart:bauxite')

    // prevent easy dirt
    event.addBlockLootModifier('minecraft:dirt_path')
        .replaceLoot('minecraft:dirt', 'minecraft:coarse_dirt')

});